import { Food } from "./app/shared/interfaces/Food";
import { TagModelModule } from "./app/shared/models/tag-model/tag-model-module";

export const sample_food: Food[] = [
{
    id:'1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    description: 'A flatbread base topped with tomato sauce, cheese, and pepperoni',
    stars: 4.5,
    imageUrl: 'food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
},
{
    id:'2',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    description: 'A small, round ball of ground meat,mixed with other ingredients',
    stars: 4.7,
    imageUrl: 'food-2.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id:'3',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    description: 'A sandwich consisting of a patty of ground meat beef or chicken',
    stars: 3.5,
    imageUrl: 'food-3.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id:'4',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    description: 'potatoes cooked in hot oil, fat, or grease, often deep-fried, and can be served as a side dish or snack',
    stars: 3.3,
    imageUrl: 'food-4.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'5',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    description: 'a soup made from chicken, simmered in water, usually with various other ingredients',
    stars: 3.0,
    imageUrl: 'food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'6',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    description: 'I like to top it with broccoli, radish, onion, bell pepper, carrot, and celery,',
    stars: 4.0,
    imageUrl: 'food-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
]

export const sample_tags: TagModelModule[] = [
  {name: 'FastFood', count: 4},
  {name: 'Pizza', count: 3},
  {name: 'Lunch', count: 3},
  {name: 'SlowFood', count: 2},
  {name: 'Hamburger', count: 1},
  {name: 'Fry', count: 5},
  {name: 'Soup', count: 1},
]